In [27]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

import warnings
warnings.filterwarnings('ignore')

In [61]:
data = pd.read_csv(r"C:\Users\Shaik Sakhlaih\Downloads\apple_sales_2024.csv")
data

,State,Region,iPhone Sales (in million units),iPad Sales (in million units),Mac Sales (in million units),Wearables (in million units),Services Revenue (in billion $)
0,Chongqing,Greater China,7.46,6.75,1.19,5.88,15.88
1,Germany,Europe,8.63,14.06,7.03,7.42,10.12
2,UK,Europe,5.61,14.09,8.78,8.19,19.85
3,Shanghai,Greater China,7.82,7.97,9.78,2.28,6.16
4,Thailand,Rest of Asia,16.70,8.13,6.46,3.48,13.29
...,...,...,...,...,...,...,...
995,Mexico,Rest of World,29.86,10.30,7.40,9.60,18.56
996,Texas,North America,27.83,12.52,8.89,4.46,6.38
997,Germany,Europe,25.47,7.69,7.90,6.90,15.00
998,Shenzhen,Greater China,15.34,8.81,8.24,8.78,15.49
999,Shanghai,Greater China,26.30,4.06,3.41,5.69,14.29

In [62]:
data.head()

,State,Region,iPhone Sales (in million units),iPad Sales (in million units),Mac Sales (in million units),Wearables (in million units),Services Revenue (in billion $)
0,Chongqing,Greater China,7.46,6.75,1.19,5.88,15.88
1,Germany,Europe,8.63,14.06,7.03,7.42,10.12
2,UK,Europe,5.61,14.09,8.78,8.19,19.85
3,Shanghai,Greater China,7.82,7.97,9.78,2.28,6.16
4,Thailand,Rest of Asia,16.70,8.13,6.46,3.48,13.29

In [63]:
data.tail()

,State,Region,iPhone Sales (in million units),iPad Sales (in million units),Mac Sales (in million units),Wearables (in million units),Services Revenue (in billion $)
995,Mexico,Rest of World,29.86,10.30,7.40,9.60,18.56
996,Texas,North America,27.83,12.52,8.89,4.46,6.38
997,Germany,Europe,25.47,7.69,7.90,6.90,15.00
998,Shenzhen,Greater China,15.34,8.81,8.24,8.78,15.49
999,Shanghai,Greater China,26.30,4.06,3.41,5.69,14.29

In [64]:
data.describe()

,iPhone Sales (in million units),iPad Sales (in million units),Mac Sales (in million units),Wearables (in million units),Services Revenue (in billion $)
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,17.444500,8.565880,5.555760,6.935500,12.447130
std,7.180077,3.735994,2.506491,2.951677,4.306347
min,5.030000,2.020000,1.010000,2.000000,5.010000
25%,11.447500,5.432500,3.470000,4.330000,8.710000
50%,17.130000,8.695000,5.550000,6.815000,12.205000
75%,23.715000,11.740000,7.730000,9.532500,16.252500
max,29.940000,14.990000,9.990000,12.000000,19.920000

In [65]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   State                            1000 non-null   object
 1   Region                           1000 non-null   object
 2   iPhone Sales (in million units)  1000 non-null   float64
 3   iPad Sales (in million units)    1000 non-null   float64
 4   Mac Sales (in million units)     1000 non-null   float64
 5   Wearables (in million units)     1000 non-null   float64
 6   Services Revenue (in billion $)  1000 non-null   float64
dtypes: float64(5), object(2)
memory usage: 54.8+ KB

In [66]:
data.isnull().sum()

State                              0
Region                             0
iPhone Sales (in million units)    0
iPad Sales (in million units)      0
Mac Sales (in million units)       0
Wearables (in million units)       0
Services Revenue (in billion $)    0
dtype: int64

In [67]:
data['State'].value_counts()

State
Hong Kong       50
UK              47
California      47
South Africa    47
Brazil          46
Canada          46
Shanghai        43
Shenzhen        43
France          43
Beijing         43
Australia       43
Japan           40
Chongqing       40
Mexico          39
Spain           39
Indonesia       38
Italy           38
Germany         37
New York        37
Illinois        35
South Korea     34
Thailand        33
India           33
Texas           33
Florida         26
Name: count, dtype: int64

In [68]:
data['Region'].value_counts()

Region
Rest of World    221
Greater China    219
Europe           204
Rest of Asia     178
North America    178
Name: count, dtype: int64

In [69]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data['State'] = le.fit_transform(data['State'])
data['Region'] = le.fit_transform(data['Region'])

In [70]:
data

,State,Region,iPhone Sales (in million units),iPad Sales (in million units),Mac Sales (in million units),Wearables (in million units),Services Revenue (in billion $)
0,5,1,7.46,6.75,1.19,5.88,15.88
1,8,0,8.63,14.06,7.03,7.42,10.12
2,24,0,5.61,14.09,8.78,8.19,19.85
3,17,1,7.82,7.97,9.78,2.28,6.16
4,23,3,16.70,8.13,6.46,3.48,13.29
...,...,...,...,...,...,...,...
995,15,4,29.86,10.30,7.40,9.60,18.56
996,22,2,27.83,12.52,8.89,4.46,6.38
997,8,0,25.47,7.69,7.90,6.90,15.00
998,18,1,15.34,8.81,8.24,8.78,15.49
999,17,1,26.30,4.06,3.41,5.69,14.29

In [71]:
data.columns

Index(['State', 'Region', 'iPhone Sales (in million units)',
       'iPad Sales (in million units)', 'Mac Sales (in million units)',
       'Wearables (in million units)', 'Services Revenue (in billion $)'],
      dtype='object')

In [72]:
data.isnull().sum()

State                              0
Region                             0
iPhone Sales (in million units)    0
iPad Sales (in million units)      0
Mac Sales (in million units)       0
Wearables (in million units)       0
Services Revenue (in billion $)    0
dtype: int64

In [73]:
x = data.drop(['Region'], axis = 1)
y = data['Region']

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=0)
print("x_train",x_train.shape)
print("x_test",x_test.shape)
print("y_train",y_train.shape)
print("y_test",y_test.shape)

x_train (700, 6)
x_test (300, 6)
y_train (700,)
y_test (300,)

In [74]:
from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB()

gnb.fit(x_train, y_train)

GaussianNB()

In [75]:
y_pred = gnb.predict(x_test)
y_pred

array([1, 1, 3, 1, 4, 1, 4, 1, 4, 1, 0, 3, 3, 0, 4, 0, 4, 1, 3, 1, 1, 1,
       1, 1, 3, 0, 0, 0, 4, 2, 4, 1, 0, 3, 3, 3, 4, 3, 3, 1, 2, 0, 4, 3,
       1, 1, 3, 4, 1, 4, 3, 0, 3, 3, 1, 3, 3, 0, 1, 4, 0, 0, 2, 4, 4, 4,
       3, 4, 3, 1, 3, 4, 3, 3, 3, 3, 1, 3, 2, 4, 1, 4, 4, 1, 1, 1, 0, 1,
       4, 3, 4, 3, 0, 0, 1, 4, 1, 0, 3, 4, 3, 0, 0, 4, 1, 1, 4, 3, 1, 0,
       0, 3, 2, 4, 1, 0, 3, 2, 4, 4, 3, 4, 3, 3, 0, 3, 0, 0, 1, 4, 1, 1,
       1, 0, 0, 3, 4, 0, 1, 0, 1, 3, 3, 1, 2, 1, 0, 3, 0, 4, 1, 0, 3, 3,
       0, 0, 1, 0, 0, 4, 0, 3, 1, 4, 0, 4, 4, 1, 1, 4, 3, 3, 4, 4, 4, 1,
       2, 3, 4, 2, 4, 3, 3, 0, 1, 0, 0, 4, 1, 0, 4, 4, 0, 2, 1, 2, 0, 4,
       4, 1, 0, 0, 1, 3, 4, 3, 0, 3, 0, 4, 4, 3, 1, 1, 3, 4, 4, 1, 0, 4,
       3, 1, 0, 4, 0, 3, 4, 0, 3, 3, 1, 0, 3, 3, 1, 0, 4, 1, 4, 3, 4, 4,
       0, 3, 1, 4, 0, 0, 0, 4, 0, 0, 3, 0, 0, 3, 1, 1, 4, 3, 4, 3, 0, 3,
       3, 4, 3, 0, 1, 3, 0, 4, 4, 4, 3, 3, 0, 0, 4, 1, 4, 4, 2, 1, 1, 1,
       4, 3, 0, 0, 1, 4, 0, 3, 3, 0, 3, 4, 2, 1])

In [76]:
from sklearn.metrics import accuracy_score
aa = accuracy_score(y_pred, y_test)*100
print("The accuracy score :",aa)

The accuracy score : 33.0